---
kind: pipeline
name: test

trigger:
  event:
  - push
  - pull_request
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: node:12
  commands:
  - scripts/ci